name: linkcheck

on:
  pull_request:
  push:

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Check for broken links
      run: sphinx-build -q --color -b linkcheck source build/linkcheck
