name: pre-commit

on:
  pull_request:
  push:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
      env:
        SKIP: rstcheck

    - name: "Generate patch file"
      if: failure()
      run: |
        git diff-index -p HEAD > "${PATCH_FILE}"
        [ -s "${PATCH_FILE}" ] && echo "UPLOAD_PATCH_FILE=${PATCH_FILE}" >> "${GITHUB_ENV}"
      env:
        PATCH_FILE: pre-commit.patch

    - name: "Upload patch artifact"
      if: failure() && env.UPLOAD_PATCH_FILE != null
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.UPLOAD_PATCH_FILE }}
        path: ${{ env.UPLOAD_PATCH_FILE }}
